//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/fy_pool_day.html
sound/ambience/sprayer.wav
gfx/env/desertbk.tga
gfx/env/desertdn.tga
gfx/env/desertft.tga
gfx/env/desertlf.tga
gfx/env/desertrt.tga
gfx/env/desertup.tga
maps/fy_pool_day.bsp
maps/fy_pool_day.txt
